-- Source: db/Lintera_dcl-5_schema.ddl (DCL_COMMERCIAL_PROPOSAL + related generator/indexes)

CREATE SEQUENCE IF NOT EXISTS gen_dcl_commercial_proposal_id START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS dcl_commercial_proposal (
    cpr_id INTEGER PRIMARY KEY DEFAULT nextval('gen_dcl_commercial_proposal_id'),
    cpr_create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usr_id_create INTEGER NOT NULL,
    cpr_edit_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usr_id_edit INTEGER NOT NULL,
    cpr_number VARCHAR(20) NOT NULL,
    cpr_date DATE NOT NULL,
    ctr_id INTEGER NOT NULL,
    cpr_concerning VARCHAR(1000),
    cpr_preamble VARCHAR(1000),
    cur_id INTEGER NOT NULL,
    cpr_course NUMERIC(18, 8),
    cpr_nds NUMERIC(15, 2),
    trm_id_price_condition INTEGER NOT NULL,
    cpr_country VARCHAR(32),
    cpr_pay_condition VARCHAR(1000),
    trm_id_delivery_condition INTEGER NOT NULL,
    cpr_delivery_address VARCHAR(256),
    cpr_sum_transport NUMERIC(15, 2),
    cpr_delivery_term VARCHAR(2000),
    cpr_add_info VARCHAR(3000),
    cpr_final_date DATE,
    usr_id INTEGER,
    cpr_proposal_received_flag SMALLINT NOT NULL DEFAULT 0,
    cpr_date_accept DATE,
    cpr_block SMALLINT,
    cpr_img_name VARCHAR(20),
    cpr_summ NUMERIC(15, 2),
    cps_id INTEGER,
    cpr_nds_by_string SMALLINT,
    cpr_sum_assembling NUMERIC(15, 2),
    cpr_old_version SMALLINT,
    cpr_check_price SMALLINT,
    cpr_check_price_date TIMESTAMP,
    usr_id_check_price INTEGER,
    cur_id_table INTEGER NOT NULL,
    cpr_assemble_minsk_store SMALLINT,
    bln_id INTEGER NOT NULL,
    cpr_all_transport SMALLINT,
    cpr_concerning_invoice VARCHAR(1000),
    cpr_can_edit_invoice SMALLINT,
    cpr_pay_condition_invoice VARCHAR(1000),
    cpr_delivery_term_invoice VARCHAR(2000),
    cpr_final_date_invoice VARCHAR(30),
    cpr_comment VARCHAR(3000),
    executor_id INTEGER,
    cpr_executor_flag SMALLINT,
    pps_id INTEGER,
    cpr_reverse_calc SMALLINT,
    cps_id_seller INTEGER,
    cps_id_customer INTEGER,
    cpr_prepay_percent NUMERIC(15, 2),
    cpr_prepay_sum NUMERIC(15, 2),
    cpr_delay_days INTEGER,
    cpr_no_reservation SMALLINT,
    cpr_provider_delivery SMALLINT,
    cpr_provider_delivery_address VARCHAR(500),
    cpr_delivery_count_day INTEGER,
    cpr_free_prices SMALLINT,
    cpr_donot_calculate_netto SMALLINT,
    cpr_print_scale INTEGER,
    cpr_contract_scale INTEGER,
    cpr_invoice_scale INTEGER,
    cpr_guaranty_in_month INTEGER,
    ctr_id_consignee INTEGER,
    cpr_final_date_above SMALLINT,
    cpr_tender_number VARCHAR(100),
    cpr_tender_number_editable CHAR(1) NOT NULL DEFAULT '0',
    cpr_proposal_declined CHAR(1) NOT NULL DEFAULT '0'
);

CREATE INDEX IF NOT EXISTS dcl_cpr_idx_date ON dcl_commercial_proposal (cpr_date);
CREATE INDEX IF NOT EXISTS idx_cpr_ctr ON dcl_commercial_proposal (ctr_id);
CREATE INDEX IF NOT EXISTS idx_cpr_usr_create ON dcl_commercial_proposal (usr_id_create);
