-- Auto-generated broad table migration from Firebird DDL
-- Review constraints/types before production cutover

CREATE TABLE IF NOT EXISTS dcl_1c_number_history (
    ID INTEGER NOT NULL,
    PRD_ID INTEGER NOT NULL,
    NUMBER_1C VARCHAR(12) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS dcl_account (
    ACC_ID INTEGER NOT NULL,
    CTR_ID INTEGER NOT NULL,
    ACC_NAME VARCHAR(100),
    ACC_ACCOUNT VARCHAR(35),
    CUR_ID INTEGER,
    ACC_INDEX SMALLINT,
    CONSTRAINT PK_DCL_ACCOUNT PRIMARY KEY (ACC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_action (
    ACT_ID INTEGER NOT NULL,
    ACT_NAME VARCHAR(100),
    ACT_SYSTEM_NAME VARCHAR(100) NOT NULL,
    ACT_LOGGING SMALLINT,
    ACT_CHECK_ACCESS SMALLINT,
    CONSTRAINT PK_DCL_ACTION PRIMARY KEY (ACT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_action_role (
    ACT_ID INTEGER NOT NULL,
    ROL_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_ACTION_ROLE PRIMARY KEY (ACT_ID, ROL_ID)
);

CREATE TABLE IF NOT EXISTS dcl_asm_list_produce (
    APR_ID INTEGER NOT NULL,
    ASM_ID INTEGER NOT NULL,
    PRD_ID INTEGER NOT NULL,
    OPR_ID INTEGER,
    APR_COUNT DECIMAL(15, 2) NOT NULL,
    CONSTRAINT PK_DCL_ASM_LIST_PRODUCE PRIMARY KEY (APR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_assemble (
    ASM_ID INTEGER NOT NULL,
    ASM_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    ASM_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    ASM_NUMBER VARCHAR(20) NOT NULL,
    ASM_DATE DATE NOT NULL,
    ASM_BLOCK SMALLINT,
    ASM_COUNT INTEGER,
    PRD_ID INTEGER NOT NULL,
    OPR_ID INTEGER,
    ASM_TYPE SMALLINT NOT NULL,
    STF_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_ASSEMBLE PRIMARY KEY (ASM_ID)
);

CREATE TABLE IF NOT EXISTS dcl_attachment (
    ATT_ID INTEGER NOT NULL,
    ATT_PARENT_ID INTEGER NOT NULL,
    ATT_PARENT_TABLE VARCHAR(32) NOT NULL,
    ATT_NAME VARCHAR(250),
    ATT_FILE_NAME VARCHAR(250),
    ATT_LINK_ID INTEGER,
    USR_ID INTEGER NOT NULL,
    ATT_CREATE_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PK_DCL_ATTACHMENT PRIMARY KEY (ATT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_blank (
    BLN_ID INTEGER NOT NULL,
    BLN_TYPE SMALLINT NOT NULL,
    BLN_NAME VARCHAR(150) NOT NULL,
    LNG_ID INTEGER NOT NULL,
    BLN_CHARSET VARCHAR(20) NOT NULL,
    BLN_PREAMBLE VARCHAR(1000),
    BLN_NOTE VARCHAR(1000),
    BLN_USAGE VARCHAR(1000),
    CONSTRAINT PK_DCL_BLANK PRIMARY KEY (BLN_ID)
);

CREATE TABLE IF NOT EXISTS dcl_blank_image (
    BIM_ID INTEGER NOT NULL,
    BLN_ID INTEGER NOT NULL,
    BIM_NAME VARCHAR(50) NOT NULL,
    BIM_IMAGE VARCHAR(32) NOT NULL,
    CONSTRAINT PK_DCL_BLANK_IMAGE PRIMARY KEY (BIM_ID)
);

CREATE TABLE IF NOT EXISTS dcl_catalog_number (
    CTN_ID INTEGER NOT NULL,
    STF_ID INTEGER NOT NULL,
    PRD_ID INTEGER NOT NULL,
    CTN_NUMBER VARCHAR(50) NOT NULL,
    MAD_ID INTEGER,
    CONSTRAINT PK_DCL_CATALOG_NUMBER PRIMARY KEY (CTN_ID),
    CONSTRAINT UNQ_DCL_CTN_PRD_ID_STF_ID UNIQUE (STF_ID, PRD_ID)
);

CREATE TABLE IF NOT EXISTS dcl_category (
    CAT_ID INTEGER NOT NULL,
    PARENT_ID INTEGER,
    CAT_NAME VARCHAR(100),
    CONSTRAINT PK_DCL_CATEGORY PRIMARY KEY (CAT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_cfc_list_produce (
    CCP_ID INTEGER NOT NULL,
    CFC_ID INTEGER NOT NULL,
    STF_ID INTEGER NOT NULL,
    PRD_ID INTEGER NOT NULL,
    CCP_PRICE DECIMAL(15, 2),
    CCP_COUNT DECIMAL(15, 2),
    CCP_NDS_RATE DECIMAL(15, 2),
    CPR_ID INTEGER,
    CONSTRAINT PK_DCL_CFC_LIST_PRODUCE PRIMARY KEY (CCP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_cfc_message (
    CCM_ID INTEGER NOT NULL,
    CFC_ID INTEGER,
    USR_ID INTEGER NOT NULL,
    CCM_CREATE_DATE TIMESTAMP NOT NULL,
    CCM_MESSAGE VARCHAR(256),
    CTR_ID INTEGER,
    CONSTRAINT PK_DCL_CFC_MESSAGE PRIMARY KEY (CCM_ID)
);

CREATE TABLE IF NOT EXISTS dcl_commercial_proposal (
    CPR_ID INTEGER NOT NULL,
    CPR_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    CPR_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    CPR_NUMBER VARCHAR(20) NOT NULL,
    CPR_DATE DATE NOT NULL,
    CTR_ID INTEGER NOT NULL,
    CPR_CONCERNING VARCHAR(1000),
    CPR_PREAMBLE VARCHAR(1000),
    CUR_ID INTEGER NOT NULL,
    CPR_COURSE DECIMAL(18, 8),
    CPR_NDS DECIMAL(15, 2),
    TRM_ID_PRICE_CONDITION INTEGER NOT NULL,
    CPR_COUNTRY VARCHAR(32),
    CPR_PAY_CONDITION VARCHAR(1000),
    TRM_ID_DELIVERY_CONDITION INTEGER NOT NULL,
    CPR_DELIVERY_ADDRESS VARCHAR(256),
    CPR_SUM_TRANSPORT DECIMAL(15, 2),
    CPR_DELIVERY_TERM VARCHAR(2000),
    CPR_ADD_INFO VARCHAR(3000),
    CPR_FINAL_DATE DATE,
    USR_ID INTEGER,
    CPR_PROPOSAL_RECEIVED_FLAG SMALLINT DEFAULT 0,
    CPR_DATE_ACCEPT DATE,
    CPR_BLOCK SMALLINT,
    CPR_IMG_NAME VARCHAR(20),
    CPR_SUMM DECIMAL(15, 2),
    CPS_ID INTEGER,
    CPR_NDS_BY_STRING SMALLINT,
    CPR_SUM_ASSEMBLING DECIMAL(15, 2),
    CPR_OLD_VERSION SMALLINT,
    CPR_CHECK_PRICE SMALLINT,
    CPR_CHECK_PRICE_DATE TIMESTAMP,
    USR_ID_CHECK_PRICE INTEGER,
    CUR_ID_TABLE INTEGER NOT NULL,
    CPR_ASSEMBLE_MINSK_STORE SMALLINT,
    BLN_ID INTEGER NOT NULL,
    CPR_ALL_TRANSPORT SMALLINT,
    CPR_CONCERNING_INVOICE VARCHAR(1000),
    CPR_CAN_EDIT_INVOICE SMALLINT,
    CPR_PAY_CONDITION_INVOICE VARCHAR(1000),
    CPR_DELIVERY_TERM_INVOICE VARCHAR(2000),
    CPR_FINAL_DATE_INVOICE VARCHAR(30),
    CPR_COMMENT VARCHAR(3000),
    EXECUTOR_ID INTEGER,
    CPR_EXECUTOR_FLAG SMALLINT,
    PPS_ID INTEGER,
    CPR_REVERSE_CALC SMALLINT,
    CPS_ID_SELLER INTEGER,
    CPS_ID_CUSTOMER INTEGER,
    CPR_PREPAY_PERCENT DECIMAL(15, 2),
    CPR_PREPAY_SUM DECIMAL(15, 2),
    CPR_DELAY_DAYS INTEGER,
    CPR_NO_RESERVATION SMALLINT,
    CPR_PROVIDER_DELIVERY SMALLINT,
    CPR_PROVIDER_DELIVERY_ADDRESS VARCHAR(500),
    CPR_DELIVERY_COUNT_DAY INTEGER,
    CPR_FREE_PRICES SMALLINT,
    CPR_DONOT_CALCULATE_NETTO SMALLINT,
    CPR_PRINT_SCALE INTEGER,
    CPR_CONTRACT_SCALE INTEGER,
    CPR_INVOICE_SCALE INTEGER,
    CPR_GUARANTY_IN_MONTH INTEGER,
    CTR_ID_CONSIGNEE INTEGER,
    CPR_FINAL_DATE_ABOVE SMALLINT,
    CPR_TENDER_NUMBER VARCHAR(100),
    CPR_TENDER_NUMBER_EDITABLE CHAR(1) DEFAULT '0' NOT NULL,
    CPR_PROPOSAL_DECLINED CHAR(1) DEFAULT '0' NOT NULL,
    CONSTRAINT PK_DCL_COMMERCIAL_PROPOSAL PRIMARY KEY (CPR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_cond_for_contract (
    CFC_ID INTEGER NOT NULL,
    CFC_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    CFC_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    CFC_PLACE SMALLINT,
    CFC_PLACE_DATE TIMESTAMP,
    USR_ID_PLACE INTEGER,
    CFC_EXECUTE SMALLINT,
    CFC_EXECUTE_DATE TIMESTAMP,
    USR_ID_EXECUTE INTEGER,
    CTR_ID INTEGER NOT NULL,
    CFC_DOC_TYPE SMALLINT NOT NULL,
    CFC_CON_NUMBER_TXT VARCHAR(200),
    CFC_CON_DATE DATE,
    CUR_ID INTEGER,
    CON_ID INTEGER,
    CFC_SPC_NUMBER_TXT VARCHAR(200),
    CFC_SPC_DATE DATE,
    CFC_PAY_COND VARCHAR(2500),
    CFC_DELIVERY_COND VARCHAR(2500),
    CFC_GUARANTEE_COND VARCHAR(2500),
    CFC_MONTAGE_COND VARCHAR(2500),
    CFC_DATE_CON_TO DATE,
    CFC_COUNT_DELIVERY VARCHAR(1000),
    CPS_ID_SIGN INTEGER,
    CPS_ID INTEGER,
    CFC_DELIVERY_COUNT SMALLINT,
    CFC_CUSTOM_POINT VARCHAR(500),
    PPS_ID INTEGER,
    CFC_COMMENT VARCHAR(1000),
    CFC_NEED_INVOICE SMALLINT,
    CFC_CHECK_PRICE SMALLINT,
    CFC_CHECK_PRICE_DATE TIMESTAMP,
    USR_ID_CHECK_PRICE INTEGER,
    SLN_ID INTEGER,
    CFC_ANNUL SMALLINT,
    CFC_ANNUL_DATE DATE,
    USR_ID_EDIT_ANNUL INTEGER,
    CFC_EDIT_ANNUL_DATE TIMESTAMP,
    CONSTRAINT PK_DCL_COND_FOR_CONTRACT PRIMARY KEY (CFC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_contact_person (
    CPS_ID INTEGER NOT NULL,
    CTR_ID INTEGER NOT NULL,
    CPS_NAME VARCHAR(200) NOT NULL,
    CPS_PHONE VARCHAR(150),
    CPS_FAX VARCHAR(150),
    CPS_BLOCK SMALLINT,
    CPS_POSITION VARCHAR(150),
    CPS_ON_REASON VARCHAR(150),
    CPS_EMAIL VARCHAR(50),
    CPS_MOB_PHONE VARCHAR(150),
    CPS_CONTRACT_COMMENT VARCHAR(300),
    CPS_FIRE SMALLINT,
    CONSTRAINT PK_DCL_CONTACT_PERSON PRIMARY KEY (CPS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_contact_person_user (
    CPS_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    CONSTRAINT UNQ1_DCL_CONTACT_PERSON_USER UNIQUE (CPS_ID, USR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_contract (
    CON_ID INTEGER NOT NULL,
    CON_CREATE_DATE TIMESTAMP,
    USR_ID_CREATE INTEGER,
    CON_EDIT_DATE TIMESTAMP,
    USR_ID_EDIT INTEGER,
    CON_NUMBER VARCHAR(50) NOT NULL,
    CON_DATE DATE NOT NULL,
    CTR_ID INTEGER,
    CUR_ID INTEGER,
    CON_EXECUTED SMALLINT,
    CON_SUMM DECIMAL(15, 2),
    CON_ORIGINAL SMALLINT,
    CON_ANNUL SMALLINT,
    CON_ANNUL_DATE DATE,
    CON_COMMENT VARCHAR(5000),
    SLN_ID INTEGER,
    CON_REUSABLE SMALLINT,
    CON_FINAL_DATE DATE,
    CONSTRAINT PK_DCL_CONTRACT PRIMARY KEY (CON_ID)
);

CREATE TABLE IF NOT EXISTS dcl_contractor (
    CTR_ID INTEGER NOT NULL,
    CTR_NAME VARCHAR(200) NOT NULL,
    CTR_EMAIL VARCHAR(40),
    CTR_BANK_PROPS VARCHAR(800),
    CTR_UNP VARCHAR(15),
    CTR_FULL_NAME VARCHAR(300),
    CTR_BLOCK SMALLINT,
    CTR_CREATE_DATE TIMESTAMP,
    USR_ID_CREATE INTEGER,
    CTR_EDIT_DATE TIMESTAMP,
    USR_ID_EDIT INTEGER,
    RPT_ID INTEGER NOT NULL,
    CTR_OKPO VARCHAR(15),
    CTR_PHONE VARCHAR(100),
    CTR_FAX VARCHAR(100),
    CTR_DOUBLE_ACCOUNT SMALLINT,
    CUT_ID INTEGER NOT NULL,
    CTR_INDEX VARCHAR(20),
    CTR_REGION VARCHAR(50),
    CTR_PLACE VARCHAR(50),
    CTR_STREET VARCHAR(50),
    CTR_BUILDING VARCHAR(10),
    CTR_ADD_INFO VARCHAR(1000),
    CTR_COMMENT VARCHAR(5000),
    CONSTRAINT PK_DCL_CONTRACTOR PRIMARY KEY (CTR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_contractor_request (
    CRQ_ID INTEGER NOT NULL,
    CRQ_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    CRQ_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    CRQ_RECEIVE_DATE DATE NOT NULL,
    CTR_ID INTEGER NOT NULL,
    CPS_ID INTEGER,
    CRQ_REQUEST_TYPE_ID INTEGER NOT NULL,
    CON_ID INTEGER,
    LPS_ID INTEGER,
    PRD_ID INTEGER,
    CRQ_NUMBER VARCHAR(15) NOT NULL,
    CRQ_DELIVER SMALLINT,
    USR_ID_MANAGER INTEGER,
    USR_ID_CHIEF INTEGER,
    USR_ID_SPECIALIST INTEGER,
    CRQ_CITY VARCHAR(50),
    CTR_ID_OTHER INTEGER,
    CRQ_NO_CONTRACT SMALLINT,
    STF_ID INTEGER,
    CRQ_SERIAL_NUM VARCHAR(100),
    CRQ_YEAR_OUT VARCHAR(100),
    CRQ_ENTER_IN_USE_DATE DATE,
    CRQ_ANNUL SMALLINT,
    CRQ_TICKET_NUMBER VARCHAR(30),
    SLN_ID INTEGER,
    CRQ_COMMENT VARCHAR(2000),
    CRQ_OPERATING_TIME DECIMAL(8, 2),
    CON_ID_FOR_WORK INTEGER,
    CONSTRAINT PK_DCL_CONTRACTOR_REQUEST PRIMARY KEY (CRQ_ID)
);

CREATE TABLE IF NOT EXISTS dcl_contractor_user (
    CTR_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    CONSTRAINT UNQ1_DCL_CONTRACTOR_USER UNIQUE (CTR_ID, USR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_contract_closed (
    CTC_ID INTEGER NOT NULL,
    CTC_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    CTC_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    CTC_NUMBER INTEGER NOT NULL,
    CTC_DATE DATE NOT NULL,
    CTC_BLOCK SMALLINT,
    CONSTRAINT PK_DCL_CONTRACT_CLOSED PRIMARY KEY (CTC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_con_list_spec (
    SPC_ID INTEGER NOT NULL,
    CON_ID INTEGER NOT NULL,
    SPC_NUMBER VARCHAR(50),
    SPC_DATE DATE,
    SPC_SUMM DECIMAL(15, 2),
    SPC_SUMM_NDS DECIMAL(15, 2),
    SPC_EXECUTED SMALLINT,
    SPC_NDS_RATE DECIMAL(15, 2),
    SPC_DELIVERY_DATE DATE,
    SPC_ADD_PAY_COND VARCHAR(5000),
    SPC_ORIGINAL SMALLINT,
    SPC_MONTAGE SMALLINT,
    SPC_GROUP_DELIVERY SMALLINT,
    SPC_DELIVERY_COND VARCHAR(5000),
    SPC_DELIVERY_TERM_TYPE SMALLINT,
    SPC_PERCENT_OR_SUM SMALLINT,
    SPC_DELIVERY_PERCENT DECIMAL(15, 2),
    SPC_DELIVERY_SUM DECIMAL(15, 2),
    SPC_PAY_AFTER_MONTAGE SMALLINT,
    SPC_ANNUL SMALLINT,
    SPC_ANNUL_DATE DATE,
    SPC_COMMENT VARCHAR(5000),
    USR_ID INTEGER,
    SPC_LETTER1_DATE DATE,
    SPC_LETTER2_DATE DATE,
    SPC_LETTER3_DATE DATE,
    SPC_COMPLAINT_IN_COURT_DATE DATE,
    SPC_ADDITIONAL_DAYS_COUNT INTEGER,
    CONSTRAINT PK_DCL_CON_LIST_SPEC PRIMARY KEY (SPC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_con_message (
    CMS_ID INTEGER NOT NULL,
    CON_ID INTEGER,
    SPC_ID INTEGER,
    USR_ID INTEGER NOT NULL,
    CMS_CREATE_DATE TIMESTAMP NOT NULL,
    CMS_MESSAGE VARCHAR(256),
    CTR_ID INTEGER,
    CONSTRAINT PK_DCL_CON_MESSAGE PRIMARY KEY (CMS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_country (
    CUT_ID INTEGER NOT NULL,
    CUT_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    CUT_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    CUT_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_DCL_COUNTRY PRIMARY KEY (CUT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_cpr_list_produce (
    LPR_ID INTEGER NOT NULL,
    CPR_ID INTEGER NOT NULL,
    LPR_PRODUCE_NAME VARCHAR(1000),
    LPR_PRICE_NETTO DECIMAL(15, 2),
    LPR_COUNT DECIMAL(15, 2),
    CUS_ID INTEGER,
    LPR_COEFICIENT DECIMAL(18, 8),
    LPR_CATALOG_NUM VARCHAR(50),
    STF_ID INTEGER,
    PRD_ID INTEGER,
    LPR_COMMENT VARCHAR(5000),
    LPC_ID INTEGER,
    LPR_SALE_PRICE DECIMAL(15, 2),
    LPR_SALE_COST_PARKING_TRANS DECIMAL(15, 2),
    LPR_PRICE_BRUTTO DECIMAL(15, 2),
    LPR_DISCOUNT DECIMAL(15, 2),
    CONSTRAINT PK_DCL_CPR_LIST_PRODUCE PRIMARY KEY (LPR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_cpr_transport (
    TRN_ID INTEGER NOT NULL,
    CPR_ID INTEGER NOT NULL,
    STF_ID INTEGER,
    TRN_SUM DECIMAL(15, 2) NOT NULL,
    CONSTRAINT PK_DCL_CPR_TRANSPORT PRIMARY KEY (TRN_ID)
);

CREATE TABLE IF NOT EXISTS dcl_crq_ord_link (
    CRQ_ID INTEGER NOT NULL,
    ORD_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS dcl_crq_print (
    CRP_ID INTEGER NOT NULL,
    CRQ_ID INTEGER NOT NULL,
    CRP_RECLAMATION_DATE DATE,
    CRP_LINTERA_REQUEST_DATE DATE,
    CRP_NO_DEFECT_ACT SMALLINT,
    CRP_LINTERA_AGREEMENT_DATE DATE,
    CRP_DELIVER SMALLINT,
    CRP_NO_RECLAMATION_ACT SMALLINT,
    CONSTRAINT PK_DCL_CRQ_PRINT PRIMARY KEY (CRP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_crq_stage (
    CRS_ID INTEGER NOT NULL,
    CRQ_ID INTEGER NOT NULL,
    CRS_NAME VARCHAR(500) NOT NULL,
    CRS_COMMENT VARCHAR(2000),
    CRS_PRINT SMALLINT,
    CONSTRAINT PK_DCL_CRQ_STAGE PRIMARY KEY (CRS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ctc_list (
    LCC_ID INTEGER NOT NULL,
    CTC_ID INTEGER NOT NULL,
    SPC_ID INTEGER NOT NULL,
    LCC_CHARGES DECIMAL(15, 2) NOT NULL,
    LCC_MONTAGE DECIMAL(15, 2) NOT NULL,
    LCC_TRANSPORT DECIMAL(15, 2) NOT NULL,
    LCC_UPDATE_SUM DECIMAL(15, 2) NOT NULL,
    CONSTRAINT PK_DCL_CTC_LIST PRIMARY KEY (LCC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ctc_pay (
    LCC_ID INTEGER NOT NULL,
    LPS_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_CTC_PAY_LCC PRIMARY KEY (LPS_ID, LCC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ctc_shp (
    LCC_ID INTEGER NOT NULL,
    SHP_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_LCC_SHP PRIMARY KEY (SHP_ID, LCC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_currency (
    CUR_ID INTEGER NOT NULL,
    CUR_NAME VARCHAR(10) NOT NULL,
    CUR_NO_ROUND SMALLINT,
    CUR_SORT_ORDER SMALLINT,
    CONSTRAINT PK_DCL_CURRENCY PRIMARY KEY (CUR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_currency_rate (
    CRT_ID INTEGER NOT NULL,
    CUR_ID INTEGER NOT NULL,
    CRT_DATE DATE NOT NULL,
    CRT_RATE DECIMAL(15, 6) NOT NULL,
    CONSTRAINT PK_DCL_CURRENCY_RATE PRIMARY KEY (CRT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_custom_code (
    CUS_ID INTEGER NOT NULL,
    CUS_CODE VARCHAR(10) NOT NULL,
    CUS_DESCRIPTION VARCHAR(500),
    CUS_PERCENT DECIMAL(15, 2) NOT NULL,
    CUS_INSTANT TIMESTAMP NOT NULL,
    CUS_CREATE_DATE TIMESTAMP,
    CUS_ID_CREATE INTEGER,
    CUS_EDIT_DATE TIMESTAMP,
    CUS_ID_EDIT INTEGER,
    USR_CREATE_DATE TIMESTAMP,
    USR_ID_CREATE INTEGER,
    USR_EDIT_DATE TIMESTAMP,
    USR_ID_EDIT INTEGER,
    CUS_LAW_240_FLAG SMALLINT,
    CUS_BLOCK SMALLINT,
    CONSTRAINT PK_DCL_CUSTOM_CODE PRIMARY KEY (CUS_ID),
    CONSTRAINT PK_DCL_CUSTOM_CODE_CI UNIQUE (CUS_CODE, CUS_INSTANT)
);

CREATE TABLE IF NOT EXISTS dcl_cus_code_history (
    ID INTEGER NOT NULL,
    PRD_ID INTEGER NOT NULL,
    CUS_CODE VARCHAR(10) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    CONSTRAINT PK_DCL_CUS_CODE_HISTORY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS dcl_delivery_request (
    DLR_ID INTEGER NOT NULL,
    DLR_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    DLR_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    DLR_PLACE_DATE TIMESTAMP,
    USR_ID_PLACE INTEGER,
    DLR_NUMBER VARCHAR(20) NOT NULL,
    DLR_DATE DATE NOT NULL,
    DLR_FAIR_TRADE SMALLINT,
    DLR_WHEREFROM VARCHAR(100),
    DLR_COMMENT VARCHAR(5000),
    DLR_PLACE_REQUEST SMALLINT,
    DLR_INCLUDE_IN_SPEC SMALLINT,
    DLR_ANNUL SMALLINT,
    DLR_NEED_DELIVER SMALLINT,
    DLR_ORD_NOT_FORM SMALLINT,
    DLR_EXECUTED SMALLINT,
    DLR_GUARANTEE_REPAIR SMALLINT,
    DLR_MINSK SMALLINT,
    CONSTRAINT PK_DCL_DELIVERY_REQUEST PRIMARY KEY (DLR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_department (
    DEP_ID INTEGER NOT NULL,
    DEP_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DCL_DEPARTMENT PRIMARY KEY (DEP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_dlr_list_produce (
    DRP_ID INTEGER NOT NULL,
    DLR_ID INTEGER NOT NULL,
    PRD_ID INTEGER NOT NULL,
    OPR_ID INTEGER,
    DRP_PRICE DECIMAL(15, 2) NOT NULL,
    DRP_COUNT DECIMAL(15, 2) NOT NULL,
    STF_ID INTEGER NOT NULL,
    CTR_ID INTEGER,
    PRS_ID INTEGER,
    DRP_PURPOSE VARCHAR(500),
    SIP_ID INTEGER,
    RECEIVE_MANAGER_ID INTEGER,
    RECEIVE_DATE DATE,
    APR_ID INTEGER,
    ASM_ID INTEGER,
    DRP_MAX_EXTRA SMALLINT,
    SPC_ID INTEGER,
    CONSTRAINT PK_DCL_DLR_LIST_PRODUCE PRIMARY KEY (DRP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_field_comment (
    FCM_ID INTEGER NOT NULL,
    FCM_KEY VARCHAR(124) NOT NULL,
    FCM_VALUE VARCHAR(4000),
    CONSTRAINT PK_DCL_FIELD_COMMENT PRIMARY KEY (FCM_ID)
);

CREATE TABLE IF NOT EXISTS dcl_files_path (
    FLP_ID INTEGER NOT NULL,
    FLP_TABLE_NAME VARCHAR(32) NOT NULL,
    FLP_PATH VARCHAR(1024) NOT NULL,
    FLP_DESCRIPTION VARCHAR(200),
    CONSTRAINT PK_DCL_FILES_PATH PRIMARY KEY (FLP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_inf_message (
    INM_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    INM_CREATE_DATE TIMESTAMP NOT NULL,
    INM_MESSAGE VARCHAR(5000),
    CONSTRAINT PK_DCL_INF_MESSAGE PRIMARY KEY (INM_ID)
);

CREATE TABLE IF NOT EXISTS dcl_instruction (
    INS_ID INTEGER NOT NULL,
    INS_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    INS_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    IST_ID INTEGER NOT NULL,
    INS_NUMBER VARCHAR(100),
    INS_DATE_SIGN DATE NOT NULL,
    INS_DATE_FROM DATE NOT NULL,
    INS_DATE_TO DATE,
    INS_CONCERNING VARCHAR(5000),
    CONSTRAINT PK_DCL_INSTRUCTION PRIMARY KEY (INS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_instruction_type (
    IST_ID INTEGER NOT NULL,
    IST_NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PK_DCL_INSTRUCTION_TYPE PRIMARY KEY (IST_ID)
);

CREATE TABLE IF NOT EXISTS dcl_language (
    LNG_ID INTEGER NOT NULL,
    LNG_NAME VARCHAR(32) NOT NULL,
    LNG_LETTER_ID VARCHAR(2) NOT NULL,
    CONSTRAINT PK_DCL_LANGUAGE PRIMARY KEY (LNG_ID)
);

CREATE TABLE IF NOT EXISTS dcl_log (
    LOG_ID INTEGER NOT NULL,
    ACT_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    LOG_TIME TIMESTAMP NOT NULL,
    LOG_IP VARCHAR(20) NOT NULL,
    CONSTRAINT PK_DCL_LOG PRIMARY KEY (LOG_ID)
);

CREATE TABLE IF NOT EXISTS dcl_lps_list_manager (
    LMN_ID INTEGER NOT NULL,
    LPS_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    LMN_PERCENT DECIMAL(3, 0) NOT NULL,
    CONSTRAINT PK_DCL_LPS_LIST_MANAGER PRIMARY KEY (LMN_ID)
);

CREATE TABLE IF NOT EXISTS dcl_montage_adjustment (
    MAD_ID INTEGER NOT NULL,
    STF_ID INTEGER NOT NULL,
    MAD_MACHINE_TYPE VARCHAR(1000) NOT NULL,
    MAD_COMPLEXITY VARCHAR(10) NOT NULL,
    MAD_ANNUL SMALLINT,
    CONSTRAINT PK_DCL_MONTAGE_ADJUSTMENT PRIMARY KEY (MAD_ID)
);

CREATE TABLE IF NOT EXISTS dcl_montage_adjustment_h (
    MADH_ID INTEGER NOT NULL,
    MAD_ID INTEGER NOT NULL,
    MAD_DATE_FROM DATE NOT NULL,
    MAD_MECH_WORK_TARIFF DECIMAL(15, 1) NOT NULL,
    MAD_MECH_WORK_RULE_MONTAGE DECIMAL(15, 1) NOT NULL,
    MAD_MECH_WORK_RULE_ADJUSTMENT DECIMAL(15, 1) NOT NULL,
    MAD_MECH_ROAD_TARIFF DECIMAL(15, 1) NOT NULL,
    MAD_MECH_ROAD_RULE DECIMAL(15, 1) NOT NULL,
    MAD_EL_WORK_TARIFF DECIMAL(15, 1) NOT NULL,
    MAD_EL_WORK_RULE_MONTAGE DECIMAL(15, 1) NOT NULL,
    MAD_EL_WORK_RULE_ADJUSTMENT DECIMAL(15, 1) NOT NULL,
    MAD_EL_ROAD_TARIFF DECIMAL(15, 1) NOT NULL,
    MAD_EL_ROAD_RULE DECIMAL(15, 1) NOT NULL,
    MAD_MECH_TOTAL DECIMAL(15, 1) NOT NULL,
    MAD_EL_TOTAL DECIMAL(15, 1) NOT NULL,
    CONSTRAINT PK_DCL_MONTAGE_ADJUSTMENT_H PRIMARY KEY (MADH_ID)
);

CREATE TABLE IF NOT EXISTS dcl_opr_list_executed (
    OPR_ID INTEGER NOT NULL,
    OPR_COUNT_EXECUTED DECIMAL(15, 2),
    OPR_DATE_EXECUTED DATE,
    OPR_FICTIVE_EXECUTED SMALLINT
);

CREATE TABLE IF NOT EXISTS dcl_order (
    ORD_ID INTEGER NOT NULL,
    ORD_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    ORD_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    ORD_NUMBER VARCHAR(15) NOT NULL,
    ORD_DATE DATE NOT NULL,
    CTR_ID INTEGER NOT NULL,
    CPS_ID INTEGER,
    ORD_CONCERNING VARCHAR(1000),
    ORD_PREAMBLE VARCHAR(1000),
    TRM_ID INTEGER,
    ORD_ADDR VARCHAR(256),
    ORD_PAY_CONDITION VARCHAR(300),
    ORD_DELIVERY_TERM VARCHAR(300),
    ORD_ADD_INFO VARCHAR(5000),
    USR_ID_DIRECTOR INTEGER,
    USR_ID_LOGIST INTEGER,
    USR_ID_DIRECTOR_RB INTEGER,
    USR_ID_CHIEF_DEP INTEGER,
    USR_ID_MANAGER INTEGER,
    CTR_ID_FOR INTEGER,
    SPC_ID INTEGER,
    STF_ID INTEGER NOT NULL,
    ORD_SENT_TO_PROD_DATE DATE,
    ORD_RECEIVED_CONF_DATE DATE,
    ORD_NUM_CONF VARCHAR(200),
    ORD_DATE_CONF DATE,
    ORD_CONF_SENT_DATE DATE,
    ORD_EXECUTED_DATE DATE,
    ORD_SUMM DECIMAL(15, 2),
    ORD_BLOCK SMALLINT,
    ORD_DELIVERY_COST_BY VARCHAR(50),
    ORD_DELIVERY_COST DECIMAL(15, 2),
    ORD_DONOT_CALCULATE_NETTO SMALLINT,
    CUR_ID INTEGER NOT NULL,
    ORD_INCLUDE_NDS SMALLINT,
    ORD_NDS_RATE DECIMAL(15, 2),
    ORD_DISCOUNT_ALL SMALLINT,
    ORD_DISCOUNT DECIMAL(15, 2),
    ORD_COUNT_ITOG_FLAG SMALLINT,
    ORD_ADD_REDUCTION_FLAG SMALLINT,
    ORD_ADD_REDUCTION DECIMAL(15, 2),
    ORD_ADD_RED_PRE_PAY_FLAG SMALLINT,
    ORD_ADD_RED_PRE_PAY DECIMAL(15, 2),
    ORD_ALL_INCLUDE_IN_SPEC SMALLINT,
    ORD_ANNUL SMALLINT,
    ORD_READY_FOR_DELIV_DATE DATE,
    ORD_IN_ONE_SPEC SMALLINT,
    ORD_COMMENT VARCHAR(3000),
    ORD_DATE_CONF_ALL SMALLINT,
    ORD_READY_FOR_DELIV_DATE_ALL SMALLINT,
    SDT_ID INTEGER,
    ORD_SHP_DOC_NUMBER VARCHAR(60),
    ORD_BY_GUARANTY SMALLINT,
    BLN_ID INTEGER NOT NULL,
    ORD_ARRIVE_IN_LITHUANIA DATE,
    ORD_SHIP_FROM_STOCK DATE,
    ORD_PRINT_SCALE INTEGER,
    ORD_LETTER_SCALE INTEGER,
    ORD_COMMENT_COVERING_LETTER VARCHAR(1000),
    SLN_ID INTEGER,
    SLN_ID_FOR_WHO INTEGER NOT NULL,
    ORD_LOGIST_SIGNATURE SMALLINT,
    ORD_DIRECTOR_RB_SIGNATURE SMALLINT,
    ORD_CHIEF_DEP_SIGNATURE SMALLINT,
    ORD_MANAGER_SIGNATURE SMALLINT,
    CONSTRAINT PK_DCL_ORDER PRIMARY KEY (ORD_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ord_list_payment (
    ORP_ID INTEGER NOT NULL,
    ORD_ID INTEGER NOT NULL,
    ORP_PERCENT DECIMAL(11, 5) NOT NULL,
    ORP_SUM DECIMAL(15, 2) NOT NULL,
    ORP_DATE DATE,
    CONSTRAINT PK_DCL_ORD_LIST_PAYMENT PRIMARY KEY (ORP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ord_list_pay_sum (
    OPS_ID INTEGER NOT NULL,
    ORD_ID INTEGER NOT NULL,
    OPS_SUM DECIMAL(15, 2) NOT NULL,
    OPS_DATE DATE,
    CONSTRAINT PK_DCL_ORD_LIST_PAY_SUM PRIMARY KEY (OPS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ord_list_produce (
    OPR_ID INTEGER NOT NULL,
    ORD_ID INTEGER NOT NULL,
    OPR_PRODUCE_NAME VARCHAR(1000),
    OPR_CATALOG_NUM VARCHAR(50),
    OPR_COUNT DECIMAL(15, 2),
    OPR_PRICE_BRUTTO DECIMAL(15, 2),
    OPR_DISCOUNT DECIMAL(15, 2),
    OPR_PRICE_NETTO DECIMAL(15, 2),
    OPR_SUMM DECIMAL(15, 2),
    OPR_USE_PREV_NUMBER CHAR(1),
    PRD_ID INTEGER NOT NULL,
    OPR_COMMENT VARCHAR(5000),
    DRP_PRICE DECIMAL(15, 2),
    CTR_ID INTEGER,
    SPC_ID INTEGER,
    OPR_PARENT_ID INTEGER,
    OPR_HAVE_DEPEND SMALLINT,
    DRP_MAX_EXTRA SMALLINT,
    CONSTRAINT PK_DCL_ORD_LIST_PRODUCE PRIMARY KEY (OPR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ord_message (
    ORM_ID INTEGER NOT NULL,
    ORD_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    ORM_CREATE_DATE TIMESTAMP NOT NULL,
    ORM_MESSAGE VARCHAR(256),
    PRC_ID INTEGER,
    CONSTRAINT PK_DCL_ORD_MESSAGE PRIMARY KEY (ORM_ID)
);

CREATE TABLE IF NOT EXISTS dcl_outgoing_letter (
    OTL_ID INTEGER NOT NULL,
    OTL_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    OTL_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    OTL_NUMBER VARCHAR(15) NOT NULL,
    OTL_DATE DATE NOT NULL,
    CTR_ID INTEGER NOT NULL,
    CPS_ID INTEGER,
    OTL_COMMENT VARCHAR(5000),
    SLN_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_OUTGOING_LETTER PRIMARY KEY (OTL_ID)
);

CREATE TABLE IF NOT EXISTS dcl_payment (
    PAY_ID INTEGER NOT NULL,
    PAY_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    PAY_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    PAY_DATE DATE NOT NULL,
    PAY_ACCOUNT VARCHAR(35),
    PAY_SUMM DECIMAL(15, 2) NOT NULL,
    CUR_ID INTEGER NOT NULL,
    PAY_COURSE DECIMAL(15, 6),
    CTR_ID INTEGER,
    PAY_BLOCK SMALLINT,
    PAY_COMMENT VARCHAR(500),
    PAY_COURSE_NBRB DECIMAL(15, 6),
    PAY_COURSE_NBRB_DATE DATE,
    CONSTRAINT PK_DCL_PAYMENT PRIMARY KEY (PAY_ID)
);

CREATE TABLE IF NOT EXISTS dcl_pay_list_summ (
    LPS_ID INTEGER NOT NULL,
    PAY_ID INTEGER NOT NULL,
    SPC_ID INTEGER NOT NULL,
    LPS_SUMM DECIMAL(15, 2),
    LPS_SUMM_EUR DECIMAL(15, 2),
    LPS_SUMM_OUT_NDS DECIMAL(15, 2),
    CONSTRAINT PK_DCL_PAY_LIST_SUMM PRIMARY KEY (LPS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_pay_message (
    PMS_ID INTEGER NOT NULL,
    PAY_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    PMS_CREATE_DATE TIMESTAMP NOT NULL,
    PMS_MESSAGE VARCHAR(512),
    PMS_SUM DECIMAL(15, 2) NOT NULL,
    CTR_ID INTEGER,
    PMS_PERCENT DECIMAL(15, 2),
    PMS_CHECK_FOR_DELETE SMALLINT,
    PMS_UPDATED SMALLINT,
    CUR_ID INTEGER,
    PMS_NO_CURATOR SMALLINT,
    CONSTRAINT PK_DCL_PAY_MESSAGE PRIMARY KEY (PMS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_prc_ctr_for_calcstate (
    LPC_ID INTEGER NOT NULL,
    PRC_ID INTEGER NOT NULL,
    CTR_ID INTEGER NOT NULL,
    CON_ID INTEGER,
    SPC_ID INTEGER,
    CONSTRAINT PK_DCL_PRC_CTR_FOR_CALCSTATE PRIMARY KEY (LPC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_prc_list_produce (
    LPC_ID INTEGER NOT NULL,
    PRC_ID INTEGER NOT NULL,
    LPC_PRODUCE_NAME VARCHAR(1000),
    STF_ID INTEGER NOT NULL,
    USR_ID INTEGER,
    LPC_COUNT DECIMAL(15, 2),
    LPC_COST_ONE DECIMAL(15, 2),
    LPC_WEIGHT DECIMAL(15, 3),
    LPC_SUMM DECIMAL(15, 2),
    LPC_SUM_TRANSPORT DECIMAL(15, 2),
    LPC_CUSTOM DECIMAL(15, 2),
    PRS_ID INTEGER NOT NULL,
    PRD_ID INTEGER NOT NULL,
    LPC_COST_ONE_LTL DECIMAL(15, 2),
    OPR_ID INTEGER,
    DRP_ID INTEGER,
    SIP_ID INTEGER,
    LPC_1C_NUMBER VARCHAR(12),
    LPC_PERCENT VARCHAR(12),
    APR_ID INTEGER,
    ASM_ID INTEGER,
    LPC_COMMENT VARCHAR(1000),
    DEP_ID INTEGER,
    LPC_COST_ONE_BY DECIMAL(15, 2) NOT NULL,
    LPC_PRICE_LIST_BY DECIMAL(15, 2),
    CONSTRAINT PK_DCL_PRC_LIST_PRODUCE PRIMARY KEY (LPC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_produce (
    PRD_ID INTEGER NOT NULL,
    CAT_ID INTEGER NOT NULL,
    PRD_NAME VARCHAR(1000),
    PRD_TYPE VARCHAR(200),
    PRD_PARAMS VARCHAR(200),
    PRD_ADD_PARAMS VARCHAR(200),
    UNT_ID INTEGER,
    CUS_CODE VARCHAR(10),
    PRD_BLOCK SMALLINT,
    PRD_CREATE_DATE TIMESTAMP,
    USR_ID_CREATE INTEGER,
    PRD_EDIT_DATE TIMESTAMP,
    USR_ID_EDIT INTEGER,
    PRD_BLOCK_DATE TIMESTAMP,
    USR_ID_BLOCK INTEGER,
    PRD_MATERIAL VARCHAR(5000),
    PRD_PURPOSE VARCHAR(5000),
    PRD_SPECIFICATION VARCHAR(5000),
    PRD_PRINCIPLE VARCHAR(5000),
    PRD_NOT_CHECK_DOUBLE SMALLINT,
    CONSTRAINT PK_DCL_PRODUCE PRIMARY KEY (PRD_ID)
);

CREATE TABLE IF NOT EXISTS dcl_produce_cost (
    PRC_ID INTEGER NOT NULL,
    PRC_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    PRC_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    PRC_NUMBER VARCHAR(50) NOT NULL,
    PRC_DATE DATE NOT NULL,
    RUT_ID INTEGER NOT NULL,
    PRC_SUM_TRANSPORT DECIMAL(15, 2),
    PRC_BLOCK SMALLINT,
    PRC_COURSE_LTL_EUR DECIMAL(15, 4),
    PRC_WEIGHT DECIMAL(15, 2),
    CONSTRAINT PK_DCL_PRODUCE_COST PRIMARY KEY (PRC_ID)
);

CREATE TABLE IF NOT EXISTS dcl_produce_cost_custom (
    PRC_ID INTEGER NOT NULL,
    LPC_PERCENT DECIMAL(15, 2),
    LPC_SUMM DECIMAL(15, 2),
    LPC_SUMM_ALLOCATION DECIMAL(15, 2)
);

CREATE TABLE IF NOT EXISTS dcl_produce_language (
    PRD_ID INTEGER NOT NULL,
    LNG_ID INTEGER NOT NULL,
    PRD_LNG_NAME VARCHAR(1000),
    CONSTRAINT PK_DCL_PRODUCE_LANGUAGE PRIMARY KEY (PRD_ID, LNG_ID)
);

CREATE TABLE IF NOT EXISTS dcl_production_term (
    PTR_ID INTEGER NOT NULL,
    OPR_ID INTEGER NOT NULL,
    PTR_COUNT DECIMAL(15, 3) NOT NULL,
    PTR_DATE DATE NOT NULL,
    PTR_COMMENT VARCHAR(900),
    CONSTRAINT PK_DCL_PRODUCTION_TERM PRIMARY KEY (PTR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_purchase_purpose (
    PPS_ID INTEGER NOT NULL,
    PPS_NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PK_DCL_PURCHASE_PURPOSE PRIMARY KEY (PPS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_purpose (
    PRS_ID INTEGER NOT NULL,
    PRS_NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PK_DCL_PURPOSE PRIMARY KEY (PRS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_rate_nds (
    RTN_ID INTEGER NOT NULL,
    RTN_DATE_FROM DATE NOT NULL,
    RTN_PERCENT DECIMAL(15, 2),
    CONSTRAINT PK_DCL_RATE_NDS PRIMARY KEY (RTN_ID)
);

CREATE TABLE IF NOT EXISTS dcl_ready_for_shipping (
    RFS_ID INTEGER NOT NULL,
    OPR_ID INTEGER NOT NULL,
    SDT_ID INTEGER NOT NULL,
    RFS_NUMBER VARCHAR(60) NOT NULL,
    RFS_COUNT DECIMAL(15, 3) NOT NULL,
    RFS_DATE DATE NOT NULL,
    RFS_WEIGHT DECIMAL(15, 3),
    RFS_GABARIT VARCHAR(300),
    RFS_COMMENT VARCHAR(900),
    RFS_ARRIVE_IN_LITHUANIA DATE,
    RFS_SHIP_FROM_STOCK DATE,
    CONSTRAINT PK_DCL_READY_FOR_SHIPPING PRIMARY KEY (RFS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_reputation (
    RPT_ID INTEGER NOT NULL,
    RPT_LEVEL SMALLINT NOT NULL,
    RPT_DESCRIPTION VARCHAR(500) NOT NULL,
    RPT_DEFAULT_IN_CTC SMALLINT,
    CONSTRAINT PK_DCL_REPUTATION PRIMARY KEY (RPT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_rests_in_minsk_temporary (
    ID INTEGER,
    DATE_CREATED TIMESTAMP,
    QUANTITY DECIMAL(15, 2),
    CONTRACTOR_NAME VARCHAR(200),
    SPECIFICATION_NUMBER VARCHAR(50),
    CONTRACT_NUMBER VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS dcl_role (
    ROL_ID INTEGER NOT NULL,
    ROL_NAME VARCHAR(32) NOT NULL,
    CONSTRAINT PK_DCL_ROLE PRIMARY KEY (ROL_ID)
);

CREATE TABLE IF NOT EXISTS dcl_route (
    RUT_ID INTEGER NOT NULL,
    RUT_NAME VARCHAR(150) NOT NULL,
    CONSTRAINT PK_DCL_ROUTE PRIMARY KEY (RUT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_seller (
    SLN_ID INTEGER NOT NULL,
    SLN_NAME VARCHAR(100) NOT NULL,
    SLN_USED_IN_ORDER SMALLINT,
    SLN_PREFIX_FOR_ORDER VARCHAR(10),
    SLN_IS_RESIDENT SMALLINT,
    CONSTRAINT PK_DCL_SELLER PRIMARY KEY (SLN_ID)
);

CREATE TABLE IF NOT EXISTS dcl_setting (
    STN_ID INTEGER NOT NULL,
    STN_NAME VARCHAR(100) NOT NULL,
    STN_DESCRIPTION VARCHAR(256),
    STN_VALUE VARCHAR(1000),
    STN_TYPE SMALLINT NOT NULL,
    STN_ACTION VARCHAR(100),
    STN_VALUE_EXTENDED VARCHAR(1000),
    CONSTRAINT PK_DCL_SETTING PRIMARY KEY (STN_ID)
);

CREATE TABLE IF NOT EXISTS dcl_shipping (
    SHP_ID INTEGER NOT NULL,
    SHP_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    SHP_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    SHP_NUMBER VARCHAR(50) NOT NULL,
    SHP_DATE DATE NOT NULL,
    SPC_ID INTEGER,
    SHP_SUMM_PLUS_NDS DECIMAL(15, 2) NOT NULL,
    CUR_ID INTEGER NOT NULL,
    SHP_BLOCK SMALLINT,
    CTR_ID INTEGER NOT NULL,
    SHP_DATE_EXPIRATION DATE,
    SHP_LETTER1_DATE DATE,
    SHP_LETTER2_DATE DATE,
    SHP_LETTER3_DATE DATE,
    SHP_COMPLAINT_IN_COURT_DATE DATE,
    SHP_COMMENT VARCHAR(3000),
    SHP_MONTAGE SMALLINT,
    CTR_ID_WHERE INTEGER,
    CON_ID_WHERE INTEGER,
    SHP_NOTICE_DATE DATE,
    SHP_SERIAL_NUM_YEAR_OUT SMALLINT,
    SHP_SUMM_TRANSPORT DECIMAL(15, 2),
    SHP_ORIGINAL SMALLINT,
    SHP_SUM_UPDATE DECIMAL(15, 2),
    CONSTRAINT PK_DCL_SHIPPING PRIMARY KEY (SHP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_shp_doc_type (
    SDT_ID INTEGER NOT NULL,
    SDT_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DCL_SHP_DOC_TYPE PRIMARY KEY (SDT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_shp_list_produce (
    LPS_ID INTEGER NOT NULL,
    SHP_ID INTEGER NOT NULL,
    LPC_ID INTEGER NOT NULL,
    STF_ID INTEGER NOT NULL,
    LPS_COUNT DECIMAL(15, 2),
    LPS_SUMM_PLUS_NDS DECIMAL(15, 2),
    LPS_ENTER_IN_USE_DATE DATE,
    LPS_MONTAGE_TIME DECIMAL(15, 1),
    LPS_MONTAGE_OFF SMALLINT,
    SHP_DATE DATE NOT NULL,
    LPS_SERIAL_NUM VARCHAR(100),
    LPS_YEAR_OUT VARCHAR(30),
    LPR_ID INTEGER,
    CONSTRAINT PK_DCL_SHP_LIST_PRODUCE PRIMARY KEY (LPS_ID)
);

CREATE TABLE IF NOT EXISTS dcl_spc_list_payment (
    SPP_ID INTEGER NOT NULL,
    SPC_ID INTEGER NOT NULL,
    SPP_PERCENT DECIMAL(11, 5) NOT NULL,
    SPP_SUM DECIMAL(15, 2) NOT NULL,
    SPP_DATE DATE,
    CONSTRAINT PK_DCL_SPC_LIST_PAYMENT PRIMARY KEY (SPP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_specification_import (
    SPI_ID INTEGER NOT NULL,
    SPI_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    SPI_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    SPI_NUMBER VARCHAR(100) NOT NULL,
    SPI_DATE DATE NOT NULL,
    SPI_COMMENT VARCHAR(2000),
    SPI_COURSE DECIMAL(15, 4),
    SPI_KOEFF DECIMAL(15, 3),
    SPI_ARRIVE SMALLINT,
    SPI_COST DECIMAL(15, 2) NOT NULL,
    SPI_SEND_DATE DATE,
    CONSTRAINT PK_DCL_SPECIFICATION_IMPORT PRIMARY KEY (SPI_ID)
);

CREATE TABLE IF NOT EXISTS dcl_spi_list_produce (
    SIP_ID INTEGER NOT NULL,
    SPI_ID INTEGER NOT NULL,
    DRP_ID INTEGER,
    SIP_PRICE DECIMAL(15, 2) NOT NULL,
    SIP_COUNT DECIMAL(15, 2) NOT NULL,
    SIP_COST DECIMAL(15, 2) NOT NULL,
    SIP_WEIGHT DECIMAL(15, 3),
    PRD_ID INTEGER NOT NULL,
    OPR_ID INTEGER,
    PRS_ID INTEGER NOT NULL,
    SIP_PERCENT DECIMAL(15, 2),
    CONSTRAINT PK_DCL_SIP_LIST_PRODUCE PRIMARY KEY (SIP_ID)
);

CREATE TABLE IF NOT EXISTS dcl_stuff_category (
    STF_ID INTEGER NOT NULL,
    STF_NAME VARCHAR(150) NOT NULL,
    STF_SHOW_IN_MONTAGE SMALLINT,
    CONSTRAINT PK_DCL_STUFF_CATEGORY PRIMARY KEY (STF_ID)
);

CREATE TABLE IF NOT EXISTS dcl_term_inco (
    TRM_ID INTEGER NOT NULL,
    TRM_NAME VARCHAR(10) NOT NULL,
    TRM_NAME_EXTENDED VARCHAR(100) NOT NULL,
    TRM_ORDER_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_TERM_INCO PRIMARY KEY (TRM_ID)
);

CREATE TABLE IF NOT EXISTS dcl_test (
    TST_ID INTEGER NOT NULL,
    TST_NAME VARCHAR(128) NOT NULL,
    TST_DECIMAL DECIMAL(15, 2),
    CONSTRAINT PK_DCL_TEST PRIMARY KEY (TST_ID)
);

CREATE TABLE IF NOT EXISTS dcl_timeboard (
    TMB_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    TMB_DATE DATE NOT NULL,
    TMB_CHECKED SMALLINT,
    TMB_CREATE_DATE TIMESTAMP NOT NULL,
    USR_ID_CREATE INTEGER NOT NULL,
    TMB_EDIT_DATE TIMESTAMP NOT NULL,
    USR_ID_EDIT INTEGER NOT NULL,
    TMB_CHECKED_DATE TIMESTAMP,
    USR_ID_CHECKED INTEGER,
    CONSTRAINT PK_DCL_TIMEBOARD PRIMARY KEY (TMB_ID)
);

CREATE TABLE IF NOT EXISTS dcl_tmb_list_work (
    TBW_ID INTEGER NOT NULL,
    TMB_ID INTEGER NOT NULL,
    TBW_DATE DATE NOT NULL,
    TBW_FROM TIME NOT NULL,
    TBW_TO TIME NOT NULL,
    TBW_HOURS_UPDATE DECIMAL(15, 2) NOT NULL,
    CRQ_ID INTEGER,
    TBW_COMMENT VARCHAR(2000),
    CONSTRAINT PK_DCL_TMB_LIST_WORK PRIMARY KEY (TBW_ID)
);

CREATE TABLE IF NOT EXISTS dcl_unit (
    UNT_ID INTEGER NOT NULL,
    IS_ACCEPTABLE_FOR_CPR CHAR(1) DEFAULT '1' NOT NULL,
    CONSTRAINT PK_DCL_UNIT PRIMARY KEY (UNT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_unit_language (
    UNT_ID INTEGER NOT NULL,
    LNG_ID INTEGER NOT NULL,
    UNT_NAME VARCHAR(150),
    CONSTRAINT PK_DCL_UNIT_LANGUAGE PRIMARY KEY (LNG_ID, UNT_ID)
);

CREATE TABLE IF NOT EXISTS dcl_user (
    USR_ID INTEGER NOT NULL,
    USR_CODE VARCHAR(3),
    USR_LOGIN VARCHAR(8),
    USR_PASSWD VARCHAR(64),
    DEP_ID INTEGER,
    USR_PHONE VARCHAR(50),
    USR_BLOCK SMALLINT,
    USR_RESPONS_PERSON SMALLINT,
    USR_NO_LOGIN SMALLINT,
    USR_CHIEF_DEP SMALLINT,
    USR_FAX VARCHAR(50),
    USR_EMAIL VARCHAR(100),
    USR_LOCAL_ENTRY SMALLINT,
    USR_INTERNET_ENTRY SMALLINT,
    CONSTRAINT PK_DCL_USER PRIMARY KEY (USR_ID)
);

CREATE TABLE IF NOT EXISTS dcl_user_language (
    USR_ID INTEGER NOT NULL,
    LNG_ID INTEGER NOT NULL,
    USR_SURNAME VARCHAR(20),
    USR_NAME VARCHAR(20),
    USR_POSITION VARCHAR(60),
    CONSTRAINT PK_DCL_USER_LANGUAGE PRIMARY KEY (USR_ID, LNG_ID)
);

CREATE TABLE IF NOT EXISTS dcl_user_link (
    ULN_ID INTEGER NOT NULL,
    USR_ID INTEGER NOT NULL,
    ULN_CREATE_DATE TIMESTAMP NOT NULL,
    ULN_URL VARCHAR(64) NOT NULL,
    ULN_PARAMETERS VARCHAR(128) NOT NULL,
    ULN_TEXT VARCHAR(500),
    ULN_MENU_ID VARCHAR(50) NOT NULL,
    CONSTRAINT PK_DCL_USER_LINK PRIMARY KEY (ULN_ID)
);

CREATE TABLE IF NOT EXISTS dcl_user_role (
    USR_ID INTEGER NOT NULL,
    ROL_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_USER_ROLE PRIMARY KEY (USR_ID, ROL_ID)
);

CREATE TABLE IF NOT EXISTS dcl_user_setting (
    UST_ID INTEGER NOT NULL,
    UST_NAME VARCHAR(100) NOT NULL,
    UST_DESCRIPTION VARCHAR(256),
    UST_VALUE VARCHAR(1000),
    UST_TYPE SMALLINT NOT NULL,
    UST_ACTION VARCHAR(100),
    UST_VALUE_EXTENDED VARCHAR(1000),
    USR_ID INTEGER NOT NULL,
    CONSTRAINT PK_DCL_USER_SETTING PRIMARY KEY (UST_ID)
);

CREATE TABLE IF NOT EXISTS dcl_year_num (
    DCL_YEAR INTEGER NOT NULL,
    DCL_NUM INTEGER NOT NULL,
    DCL_TABLE VARCHAR(64) NOT NULL,
    CONSTRAINT PK_DCL_YEAR_NUM PRIMARY KEY (DCL_YEAR, DCL_TABLE)
);

