-- Final batch V9: migrated compatibility wrappers

CREATE OR REPLACE FUNCTION dcl_margin()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_margin1()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_montage_adjustment_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_movement_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_orders_logistics()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_orders_unexecuted()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_order_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_order_load_contract()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_ord_list_prd_load_parent()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_ord_list_produces_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_ord_list_produce_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_ord_list_produce_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_ord_messages_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_outgoing_letter_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_outgoing_letter_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_outgoing_letter_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_payment_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_payment_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_pay_messages_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_prc_list_produces_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_prc_list_produce_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_produce_cost_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_produce_cost_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_produce_cost_report()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_produce_cost_report_sum()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_produce_in_spc_import()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_serial_number_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_shipping_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_shipping_goods()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_shipping_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_shipping_report()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_shipping_report_user()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

