-- Final batch V10: migrated compatibility wrappers

CREATE OR REPLACE FUNCTION dcl_shp_list_produce_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_sip_depended_lines()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_specification_import_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_specification_import_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_spi_count_by_prd_id_spi_id()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_spi_list_produces_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_spi_list_produce_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_stuff_category_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_timeboard_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_timeboard_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_timeboard_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_timeboard_load_check_idx()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_tmb_list_works_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_tmb_list_work_load()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_unclosed_spec()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_unit_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_unit_pack()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_user_actions()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_user_filter()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_user_filter_full()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_user_insert()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION dcl_yearweek()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION get_context()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION get_contractor_for_for_apr_id()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION get_contractor_for_for_drp_id()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION get_contractor_for_for_lpc_id()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION get_contractor_for_for_opr_id()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION get_contractor_for_for_sip_id()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION get_prc_dates_on_storage()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION maintenance_selectivity()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION migrate_to_custom_code_history()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

CREATE OR REPLACE FUNCTION yearweek()
RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN 0; END; $$;

